### ISSUE TITLE
Port/Adapt to Jasmine 2.0

### ISSUE THREAD

**Issue by Jonahss** [detro/jasmine-jsreporter#6]
Is there a project under-way (or finished) for providing the same functionality for Jasmine 2.0? The reporter interface was completely changed.

**Comment by detro** [comment]
No work is planned, but would be lovely if someone was to pick it up.
Are you volunteering? :)

**Comment by Jonahss** [comment]
Hee hee. I've made a note on my to-do list, but it's not near the top yet ;)

**Comment by sclevine** [comment]
Sort of done in #7.

**Comment by detro** [comment]
@sclevine while I appreciate the contribution immensely, I must say you haven't done a great job and making me believe it works - or you are just too modest? :)

Because it's essentially a total break with previous Jasmine, I'd appreciate if you couldmake certain those changes work with Jasmine 2.0 and, if possible, preserve all the functionalities.

**Comment by sclevine** [comment]
Hi @detro,

First, I don't think it's currently possible to count the number of passed expectations per spec in Jasmine 2. @alextreppass made an issue [here](https://github.com/pivotal/jasmine/issues/547). We could swap out `jasmine.Spec.prototype.addExpectationResult` with a function that counted these, but that would be very ugly and fragile.

I'm not going to claim #7 works perfectly without any (automated) tests, but it does seem to generate reasonable output for the test suites I've run it against. I'm more worried about semantics. For instance, Jasmine 2 has `disabled` and `pending` statuses, instead of just `skipped`.

**Comment by detro** [comment]
Closing.
Discussion can continue at #7.
